#!/bin/bash
#
# setup-nginx.sh - Automated NGINX installation & configuration
#

# exit on error
set -e

function show_usage {
    echo "Usage: $0 [options]"
    echo "Options:"
    echo " --help    Show this help message"
}

if [[ "$1" == "--help"]]; then
show_usage
exit 0
fi

echo "starting nginx installation..."

function install_nginx {
    echo "Installing nginx..."

    # detect OS
    if [ -f /etc/debian_version ]; then
    # debian/ubuntu
        apt-get update
        apt-get install -y nginx
    elif [ -f /etc/redhat-release]; then
    # centos/rhel
        yum install -y epel-release
        yum install -y nginx
    else
        echo "Unsupported OS. Please install Nginx manually."
        exit 1
    fi

    # verify installation
    if command -v nginx &> /dev/null; then
        echo "Nginx installed successfully!"
    else
        echo "Nginx installation failed!"
        exit 1
    fi
}

install_nginx

function configure_ports {
    echo "Configuring nginx ports.."

    local http_port=${HTTP_PORT:-80}
    local https_port=${HTTPS_PORT:-443}

    # create a port conf file
    cat > /etc/nginx/conf.d/ports.conf << EOF
# Port Configuration
# Generated by setup-nginx.sh (https://github.com/1w6ts/linux-scripts)

server {
    listen ${http_port} default_server;
    listen [::]:${http_port} default_server;

    # redirect to HTTPS if enabled
    if(\$HTTPS_ENABLED) {
        return 301 https://\$host\$request_uri;
    }

    # default server configuration will be included
    include /etc/nginx/sites-enabled/default;
}

# https server config
server {
    listen ${https_port} ssl http2;
    listen [::]:${https_port} ssl http2;

    ## ssl configuration will be included later
    # include /etc/nginx/snippets/ssl-params.conf;

    # default server config
    include /etc/nginx/sites-enabled/default;
}
EOF

    echo "Port configuration compolete: HTTP on $http_port, HTTPS on $https_port"
}

configure_ports